"""
Per-session meal planner state.

The calendar is deliberately lazy: sessions do not get a calendar.json until the
agent calls show_calendar with a real plan. The browser never reads this file
directly; routes and tools go through this module.

Everything here is a normalizer, not a validator. These rules ARE product behavior --
what survives onto disk, what gets dropped, and when a meal's cached detail becomes
stale -- so they are ported as pure functions and covered by tests rather than handed
to Pydantic, whose coercion rules differ from the hand-written JS ones.

Invalid input raises ValueError; the routers turn that into the 400 {"error": ...}
the Express routes produced.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

from ..models.session import Session
from ..persistence import files

DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
_DAY_SET = frozenset(DAYS)
MEALS = ["breakfast", "lunch", "dinner"]
_YOUTUBE_ID_RE = re.compile(r"[a-zA-Z0-9_-]{11}")
_ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def calendar_path(session: Session) -> Path:
    return session.folder / "calendar.json"


def _clean_string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} must be a non-empty string")
    return value.strip()


def _trimmed(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ""


def _normalize_ingredient(value: Any) -> dict[str, str] | None:
    """One ingredient line: a name plus a human-friendly quantity string.

    Anything without a usable name is dropped rather than raising -- the list is
    generated by an LLM, so we sanitize instead of trusting it.
    """
    if not isinstance(value, dict):
        return None
    name = _trimmed(value.get("name"))
    if not name:
        return None
    return {"name": name, "quantity": _trimmed(value.get("quantity"))}


def _normalize_nutrition(value: Any) -> dict[str, str] | None:
    """Macro breakdown for one meal.

    Kept only when at least one field has a value, so an all-empty object never
    survives onto disk.
    """
    if not isinstance(value, dict):
        return None

    nutrition = {
        "protein": _trimmed(value.get("protein")),
        "carbs": _trimmed(value.get("carbs")),
        "fat": _trimmed(value.get("fat")),
        "fiber": _trimmed(value.get("fiber")),
    }
    return nutrition if any(nutrition.values()) else None


def _first_valid_video_id(value: Any) -> str | None:
    match = _YOUTUBE_ID_RE.search(str(value or ""))
    return match.group(0) if match else None


def is_youtube_video_url(value: Any) -> bool:
    raw = str(value or "").strip()
    parsed = urlparse(raw)
    # JS `new URL()` throws on anything without a scheme + host; mirror that.
    if not parsed.scheme or not parsed.hostname:
        return False

    host = re.sub(r"^www\.", "", parsed.hostname)
    host = re.sub(r"^m\.", "", host)

    segments = [s for s in parsed.path.split("/") if s]

    if host == "youtu.be":
        return bool(_first_valid_video_id(segments[0] if segments else ""))

    if host not in ("youtube.com", "youtube-nocookie.com"):
        return False

    if parsed.path == "/watch":
        v = parse_qs(parsed.query).get("v", [""])[0]
        return bool(_first_valid_video_id(v))

    kind = segments[0] if segments else ""
    video_id = segments[1] if len(segments) > 1 else ""
    return kind in ("embed", "shorts", "live") and bool(_first_valid_video_id(video_id))


def _normalize_youtube_video(value: Any) -> dict[str, str] | None:
    if not isinstance(value, dict):
        return None
    url = _trimmed(value.get("url"))
    if not is_youtube_video_url(url):
        return None
    return {"title": _trimmed(value.get("title")), "url": url}


def _normalize_meal(value: Any, label: str) -> dict[str, Any] | None:
    if value is None:
        return None
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a meal object, null, or omitted")

    meal: dict[str, Any] = {"name": _clean_string(value.get("name"), f"{label}.name")}

    # `servings` = portions this slot needs. Only stored when greater than 1, so a
    # plain single-portion dish stays clean on disk. Coerced defensively so a bad
    # value never breaks batch scaling downstream.
    if value.get("servings") is not None:
        try:
            servings = int(float(value["servings"]))
        except (TypeError, ValueError):
            servings = 0
        if servings > 1:
            meal["servings"] = servings

    # `calories` is free text (e.g. "~450 kcal"), produced up front by the conductor
    # when it builds the plan. Accept a number too, just in case.
    if value.get("calories") is not None:
        raw = value["calories"]
        calories = raw.strip() if isinstance(raw, str) else str(raw).strip()
        if calories:
            meal["calories"] = calories

    # `ingredients`, `nutrition` and `youtubeVideos` are filled in LAZILY the first
    # time a user opens the day's card, then cached here. Presence of an
    # `ingredients` array is the "already generated" marker (even when empty), so we
    # preserve it whenever the key exists rather than only when non-empty.
    if isinstance(value.get("ingredients"), list):
        meal["ingredients"] = [
            item
            for item in (_normalize_ingredient(raw) for raw in value["ingredients"])
            if item
        ]

    nutrition = _normalize_nutrition(value.get("nutrition"))
    if nutrition:
        meal["nutrition"] = nutrition

    if isinstance(value.get("youtubeVideos"), list):
        videos = [
            video
            for video in (_normalize_youtube_video(raw) for raw in value["youtubeVideos"])
            if video
        ]
        if videos:
            meal["youtubeVideos"] = videos

    return meal


def _normalize_day(value: Any, week_index: int, day_index: int) -> dict[str, Any]:
    where = f"weeks[{week_index}].days[{day_index}]"
    if not isinstance(value, dict):
        raise ValueError(f"{where} must be an object")

    day = _clean_string(value.get("day"), f"{where}.day")
    if day not in _DAY_SET:
        raise ValueError(f'Invalid day "{day}" in {where}')

    normalized: dict[str, Any] = {"day": day, "disabled": value.get("disabled") is True}

    # A day's real calendar date (ISO YYYY-MM-DD), used to label the card. Optional so
    # older calendars without it still load -- those cards fall back to name-only.
    raw_date = value.get("date")
    if isinstance(raw_date, str) and _ISO_DATE_RE.match(raw_date.strip()):
        normalized["date"] = raw_date.strip()

    for meal in MEALS:
        normalized_meal = _normalize_meal(value.get(meal), f"{where}.{meal}")
        if normalized_meal:
            normalized[meal] = normalized_meal

    return normalized


def _normalize_weeks(value: list[Any]) -> list[dict[str, Any]]:
    weeks: list[dict[str, Any]] = []
    for week_index, week in enumerate(value):
        if not isinstance(week, dict):
            raise ValueError(f"weeks[{week_index}] must be an object")
        if not isinstance(week.get("days"), list):
            raise ValueError(f"weeks[{week_index}].days must be an array")
        weeks.append(
            {
                "id": _clean_string(week.get("id"), f"weeks[{week_index}].id"),
                "title": _clean_string(week.get("title"), f"weeks[{week_index}].title"),
                "startDate": _clean_string(
                    week.get("startDate"), f"weeks[{week_index}].startDate"
                ),
                "endDate": _clean_string(week.get("endDate"), f"weeks[{week_index}].endDate"),
                "days": [
                    _normalize_day(day, week_index, day_index)
                    for day_index, day in enumerate(week["days"])
                ],
            }
        )
    return weeks


def _normalize_ui(value: Any, weeks: list[dict[str, Any]]) -> dict[str, Any]:
    week_ids = {week["id"] for week in weeks}
    ui = value.get("ui") if isinstance(value, dict) else None
    candidate = ui.get("selectedWeekId") if isinstance(ui, dict) else None

    if isinstance(candidate, str) and candidate in week_ids:
        selected: str | None = candidate
    else:
        selected = weeks[0]["id"] if weeks else None
    return {"selectedWeekId": selected}


def normalize_calendar(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError("calendar must be an object")
    if not isinstance(value.get("weeks"), list):
        raise ValueError("weeks must be an array")

    weeks = _normalize_weeks(value["weeks"])
    return {"ui": _normalize_ui(value, weeks), "weeks": weeks}


def read(session: Session) -> tuple[bool, dict[str, Any] | None]:
    """Returns (exists, calendar)."""
    raw = files.read_json(calendar_path(session))
    if raw is None:
        return False, None
    return True, normalize_calendar(raw)


def _drop_stale_details(
    weeks: list[dict[str, Any]], previous: dict[str, Any] | None
) -> list[dict[str, Any]]:
    """Invalidate cached detail whose dish identity changed.

    The cached ingredients, nutrition and YouTube videos describe a specific dish at a
    specific batch size, so they belong to a `(name, servings)` identity. When a slot's
    name or servings changes, that cache is stale and must be dropped -- otherwise the
    conductor, which re-sends the whole calendar (details and all) on every edit, would
    carry the old list forward and the day would never regenerate.

    Removing the `ingredients` array is the whole invalidation: absence of that array
    is our single "not generated yet" marker, which both the /details route and the
    frontend already key off.
    """
    if not previous:
        return weeks

    def prior_meal(week_id: str, day_name: str, meal: str) -> dict[str, Any] | None:
        week = next((w for w in previous["weeks"] if w["id"] == week_id), None)
        if not week:
            return None
        day = next((d for d in week["days"] if d["day"] == day_name), None)
        return day.get(meal) if day else None

    result: list[dict[str, Any]] = []
    for week in weeks:
        days: list[dict[str, Any]] = []
        for day in week["days"]:
            next_day = dict(day)
            for meal in MEALS:
                incoming = next_day.get(meal)
                if not incoming or not isinstance(incoming.get("ingredients"), list):
                    continue
                prior = prior_meal(week["id"], day["day"], meal)
                same_identity = bool(
                    prior
                    and prior.get("name") == incoming.get("name")
                    and (prior.get("servings") or 1) == (incoming.get("servings") or 1)
                )
                if not same_identity:
                    next_day[meal] = {
                        key: val
                        for key, val in incoming.items()
                        if key not in ("ingredients", "nutrition", "youtubeVideos")
                    }
            days.append(next_day)
        result.append({**week, "days": days})
    return result


def write(session: Session, calendar: Any) -> dict[str, Any]:
    _, current = read(session)

    incoming = calendar
    if isinstance(incoming, dict):
        ui = incoming.get("ui") or (current.get("ui") if current else None)
        incoming = {**incoming, "ui": ui}

    normalized = normalize_calendar(incoming)
    normalized["weeks"] = _drop_stale_details(normalized["weeks"], current)
    session.folder.mkdir(parents=True, exist_ok=True)
    files.write_json(calendar_path(session), normalized)
    return normalized


def select_week(session: Session, week_id: Any) -> dict[str, Any]:
    clean_week_id = _clean_string(week_id, "weekId")
    exists, current = read(session)
    if not exists or current is None:
        raise ValueError("No calendar exists for this session yet")
    if not any(week["id"] == clean_week_id for week in current["weeks"]):
        raise ValueError(f'Week "{clean_week_id}" was not found')

    return write(
        session, {**current, "ui": {**current["ui"], "selectedWeekId": clean_week_id}}
    )


def clear_day(session: Session, week_id: Any, day: Any) -> dict[str, Any]:
    clean_week_id = _clean_string(week_id, "weekId")
    clean_day = _clean_string(day, "day")
    if clean_day not in _DAY_SET:
        raise ValueError(f'Invalid day "{clean_day}"')

    exists, current = read(session)
    if not exists or current is None:
        raise ValueError("No calendar exists for this session yet")

    changed = False
    weeks: list[dict[str, Any]] = []
    for week in current["weeks"]:
        if week["id"] != clean_week_id:
            weeks.append(week)
            continue
        changed = True
        day_exists = any(item["day"] == clean_day for item in week["days"])
        if day_exists:
            days = [
                {"day": clean_day, "disabled": True} if item["day"] == clean_day else item
                for item in week["days"]
            ]
        else:
            days = [*week["days"], {"day": clean_day, "disabled": True}]
        weeks.append({**week, "days": days})

    if not changed:
        raise ValueError(f'Week "{clean_week_id}" was not found')
    return write(session, {"ui": current["ui"], "weeks": weeks})


def set_day_details(
    session: Session, week_id: Any, day: Any, details_by_meal: dict[str, Any] | None
) -> dict[str, Any]:
    """Merge lazily-generated ingredients + nutrition into a single day's meals.

    `details_by_meal` is keyed by meal (breakfast/lunch/dinner); only meals that
    already exist on the day and have a matching entry are touched. Re-reads the
    calendar fresh before writing so a concurrent show_calendar isn't clobbered.
    """
    clean_week_id = _clean_string(week_id, "weekId")
    clean_day = _clean_string(day, "day")
    if clean_day not in _DAY_SET:
        raise ValueError(f'Invalid day "{clean_day}"')

    exists, current = read(session)
    if not exists or current is None:
        raise ValueError("No calendar exists for this session yet")

    details = details_by_meal or {}
    found = False
    weeks: list[dict[str, Any]] = []
    for week in current["weeks"]:
        if week["id"] != clean_week_id:
            weeks.append(week)
            continue
        days: list[dict[str, Any]] = []
        for item in week["days"]:
            if item["day"] != clean_day:
                days.append(item)
                continue
            found = True
            next_day = dict(item)
            for meal in MEALS:
                detail = details.get(meal)
                if next_day.get(meal, {}).get("name") and detail:
                    merged = dict(next_day[meal])
                    merged["ingredients"] = (
                        detail["ingredients"]
                        if isinstance(detail.get("ingredients"), list)
                        else []
                    )
                    if detail.get("nutrition"):
                        merged["nutrition"] = detail["nutrition"]
                    if isinstance(detail.get("youtubeVideos"), list) and detail["youtubeVideos"]:
                        merged["youtubeVideos"] = detail["youtubeVideos"]
                    next_day[meal] = merged
            days.append(next_day)
        weeks.append({**week, "days": days})

    if not found:
        raise ValueError(f'Week "{clean_week_id}" / day "{clean_day}" was not found')
    return write(session, {**current, "weeks": weeks})
